name: Trigger auto deployment for temitope234

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/temitope234-AutoDeployTrigger-8bdc06dd-10d9-44ac-8a4d-964f8087befe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TEMITOPE234_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEMITOPE234_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEMITOPE234_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: hub.docker.com
          registryUsername: ${{ secrets.TEMITOPE234_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEMITOPE234_REGISTRY_PASSWORD }}
          containerAppName: temitope234
          resourceGroup: containerapp
          imageToBuild: hub.docker.com/temitope234:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


